# setting
theme: cayman
title: Resourcing of Coal Ash Wastes for Decarbonized Infrastructure Materials
description: Establish the resource potential of coal ash wastes for cementitious materials by developing a geospatialy-resolved dataset of coal ash wastes and expected compositional charcteristics at the disposal sites of coal fired power plants.
show_downloads: false
